### ISSUE TITLE
trouble with custom commands

### ISSUE THREAD

**Issue by bappp0** [ahoys/tunnelerjs#11]
ok so i dont really get the instructions and im confused. how exactly does it work?

**Comment by ahoys** [comment]
Tunneler supports custom commands. There are plenty of **already written commands** that you can enable in configs, **or you can write your own** (if you know JavaScript). I assume you are asking about the already defined commands?

For example @Tunneler ping (or what-ever the bot's name is) in Discord makes Tunneler return latency, **if** the ping command is enabled for the Discord server and **if** you are the owner of the bot.

By default @Tunneler about, @Tunneler exit, @Tunneler ping, @Tunneler reboot and @Tunneler uptime should work. But only if the person making the commands is marked as the owner of the bot (this too can be altered).

---

[Here's an example of guild (Discord server) configs](https://github.com/ahoys/tunnelerjs/blob/master/guilds/template.json)

Inside "commands" there are various command-related settings. For example whether they are enabled (true/false) and who has access to the command. In some rare cases there may also be command-specific settings.

In "middlewares" you can enable/disable middlewares. Middlewares are something that affect all messages. For example the anti spam feature that requires reading all received messages.

---

[In readme you can find instructions on how to set the owner, see "Installation"](https://github.com/ahoys/tunnelerjs/blob/master/README.md)

**Comment by bappp0** [comment]
ok, thanks!
