### ISSUE TITLE
What is the prefix, and there is no config folder or settings.json?

### ISSUE THREAD

**Issue by DylanR210** [ahoys/tunnelerjs#3]
What is the prefix, and there is no config folder or settings.json?

**Comment by ahoys** [comment]
See the releases and download the newest 0.9.6 version to get the correct files. [Click here](https://github.com/ahoys/tunnelerjs/releases). The files you see in /tunnelerjs are for the upcoming, not released version (work in progress).

commands.json has all the available commands and their keyword (the word you say to activate the command, you can alter keywords).

settings.json has the settings. There should be 2 templates already to give some example. Just add your server e.g. 277194033301854464 and the according settings for the server. You can have different settings for different servers.

strings.json has sentences the bot says when some command is activated (you can alter these).

**Comment by DylanR210** [comment]
thank you, i am sorry
