### ISSUE TITLE
Hello the bot who is spamming 

### ISSUE THREAD

**Issue by modyamash** [ahoys/tunnelerjs#9]
every time i try to tybe any thing bot says
 stop spamming or you'll be punished.
There is no separator shown every word and the other! There is a solution to this problem.
Also when a new person enters the server the warn gives him Warn this very strange?
please  tell me how to fix this i have taird to find issue :)
and thank you for nice devlopment

**Comment by ahoys** [comment]
Hmm, it seems that Discord or Discord.js has changed something that is causing this new unwanted behavior. At least check your bot's guild settings and try to adjust the bot to be less intrusive. You can also disable the feature if you're using the bot for something else.

If you are looking for a bot that 100% prevents spam bots from entering your channel, see [https://github.com/ahoys/discaptcha](https://github.com/ahoys/discaptcha)

I'll look into this when I've got time.

**Comment by ahoys** [comment]
The bot is re-written, this is most likely solved.
